default:
  image: node:20-alpine

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - check

check:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'web'
  variables:
    NODE_ENV: test
    AIGW_TOKEN: test-token-for-ci
    AIGW_URL: https://mock-api.test.com
  cache:
    key:
      files:
        - pnpm-lock.yaml
        - .gitlab-ci.yml
    paths:
      - node_modules/
  script:
    - npm config set registry https://registry.npmmirror.com
    - npm install -g pnpm@9
    - pnpm install
    - pnpm build
    - pnpm type-check
    - pnpm lint
    - pnpm test
  tags:
    - ide-runner