package com.wave.jetbrains.bridge

import com.intellij.openapi.diagnostic.logger
import com.intellij.ui.jcef.JBCefBrowser
import com.intellij.ui.jcef.JBCefBrowserBase
import com.intellij.ui.jcef.JBCefJSQuery
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import org.cef.browser.CefBrowser
import org.cef.CefSettings
import org.cef.handler.CefDisplayHandlerAdapter
import org.cef.handler.CefLoadHandlerAdapter

/**
 * JCEF bridge wiring:
 *  - JS → Kotlin: the shim calls `window.__wavePostMessage(<json>)`, a fixed bridge function
 *    we inject on every page load. Its body calls the real CefMessageRouter function
 *    (`cefQuery_<hash>_<index>`, generated by [JBCefJSQuery.inject]) which forwards to [onMessage].
 *  - Kotlin → JS: [postMessage] calls `window.__waveReceive(<json>)`; the shim turns that
 *    into a `MessageEvent` dispatched on `window`, matching the webview's existing listener.
 */
class JcefBrowserBridge(
    private val browser: JBCefBrowser,
) {
    private val LOG = logger<JcefBrowserBridge>()
    private val json = Json { ignoreUnknownKeys = true }
    private val jsQuery: JBCefJSQuery

    /** Invoked for every message posted from the webview. */
    var onMessage: ((JsonObject) -> Unit)? = null

    init {
        jsQuery = JBCefJSQuery.create(browser as JBCefBrowserBase)
        jsQuery.addHandler { request ->
            try {
                val parsed = json.parseToJsonElement(request) as? JsonObject
                if (parsed != null) {
                    onMessage?.invoke(parsed)
                }
            } catch (e: Exception) {
                LOG.warn("Failed to parse webview message: ${e.message}")
            }
            JBCefJSQuery.Response("")
        }

        // Forward JS console output to idea.log so webview errors are visible.
        browser.jbCefClient.addDisplayHandler(object : CefDisplayHandlerAdapter() {
            override fun onConsoleMessage(
                b: CefBrowser, severity: CefSettings.LogSeverity, message: String, source: String, line: Int
            ): Boolean {
                LOG.info("[webview-console] $message ($source:$line)")
                return true
            }
        }, browser.cefBrowser)

        // Inject a stable bridge function on every page load. JBCefJSQuery's CefMessageRouter
        // registers a uniquely-named global (cefQuery_<hash>_<index>); we wrap it in a fixed
        // `window.__wavePostMessage` so the shim doesn't need to know the generated name.
        browser.jbCefClient.addLoadHandler(object : CefLoadHandlerAdapter() {
            override fun onLoadEnd(b: CefBrowser, frame: org.cef.browser.CefFrame, httpStatusCode: Int) {
                if (!frame.isMain) return
                val inject = jsQuery.inject("request")
                val script = "window.__wavePostMessage = function(request) { $inject };"
                b.executeJavaScript(script, b.url, 0)
                LOG.info("[onLoadEnd] injected __wavePostMessage bridge")
            }
        }, browser.cefBrowser)
    }

    /** Push a message from Kotlin into the webview via the shim's __waveReceive. */
    fun postMessage(command: String, payload: JsonObject) {
        val merged = JsonObject(payload.toMutableMap().apply { put("command", JsonPrimitive(command)) })
        val jsonStr = json.encodeToString(JsonObject.serializer(), merged)
        val escaped = jsonStr.replace("\\", "\\\\").replace("'", "\\'")
        executeJavaScript("window.__waveReceive('$escaped');")
    }

    fun loadUrl(url: String) {
        LOG.info("JcefBridge loading URL: $url")
        browser.loadURL(url)
    }

    private fun executeJavaScript(script: String) {
        try {
            browser.cefBrowser.executeJavaScript(script, "", 0)
        } catch (e: Exception) {
            LOG.warn("executeJavaScript failed: ${e.message}")
        }
    }

    fun dispose() {
        jsQuery.dispose()
    }
}
