# Agent Memory API Contract

openapi: 3.0.3
info:
  title: Agent Memory Management API
  description: Internal API contract for memory management in Wave Agent SDK
  version: 1.0.0

components:
  schemas:
    MemoryContent:
      type: object
      properties:
        content:
          type: string
          description: Raw memory content as string
        isEmpty:
          type: boolean
          description: Whether memory content is empty
      required: [content, isEmpty]

    MemoryType:
      type: string
      enum: [project, user]
      description: Type of memory being accessed or modified

  interfaces:
    AgentMemoryInterface:
      description: Public memory access interface for Agent class
      methods:
        projectMemory:
          type: getter
          returns: string
          description: Get project memory content (readonly)
          
        userMemory:
          type: getter  
          returns: string
          description: Get user memory content (readonly)
          
        combinedMemory:
          type: getter
          returns: string
          description: Get combined project and user memory content (readonly)
          
        saveMemory:
          type: method
          parameters:
            - name: message
              type: string
              required: true
              description: Memory message to save (starting with #)
            - name: type
              type: MemoryType
              required: true
              description: Whether to save to project or user memory
          returns: Promise<void>
          description: Save memory message to specified memory type
          errors:
            - FileWriteError: When file write operation fails
            - ValidationError: When message format is invalid

    MemoryUtilityInterface:
      description: Utility functions for memory file operations
      methods:
        readMemoryFile:
          parameters:
            - name: workdir
              type: string
              required: true
          returns: Promise<string>
          description: Read project memory file content
          
        addMemory:
          parameters:
            - name: message
              type: string
              required: true
            - name: workdir
              type: string  
              required: true
          returns: Promise<void>
          description: Add memory entry to project memory file
          
        getUserMemoryContent:
          parameters: []
          returns: Promise<string>
          description: Read user memory file content
          
        addUserMemory:
          parameters:
            - name: message
              type: string
              required: true
          returns: Promise<void>
          description: Add memory entry to user memory file

  examples:
    MemoryAccess:
      summary: Accessing memory content
      value: |
        const agent = await Agent.create({ workdir: "/path/to/project" });
        
        // Read-only access to memory content
        const projectMemory = agent.projectMemory;
        const userMemory = agent.userMemory;  
        const allMemory = agent.combinedMemory;
        
        // Save new memory (updates internal content)
        await agent.saveMemory("#Important insight about project", "project");
        await agent.saveMemory("#User preference noted", "user");

    MemoryLoading:
      summary: Memory loading during agent initialization
      value: |
        // Memory is loaded automatically during Agent.create()
        const agent = await Agent.create({ 
          workdir: "/path/to/project",
          logger: myLogger 
        });
        
        // Memory content is immediately available
        console.log("Project memory loaded:", agent.projectMemory.length);
        console.log("User memory loaded:", agent.userMemory.length);

    ErrorHandling:
      summary: Graceful error handling for missing files
      value: |
        // If memory files don't exist or are unreadable:
        // - Agent initialization continues successfully
        // - Memory getters return empty strings
        // - Errors are logged but don't throw exceptions
        
        const agent = await Agent.create({ workdir: "/nonexistent/path" });
        console.log(agent.projectMemory); // Returns "" (empty string)
        console.log(agent.userMemory);    // Returns "" (empty string)

contracts:
  breaking_changes: []
  
  backward_compatibility:
    - All existing Agent class public methods maintain signatures
    - Memory utility functions preserve existing behavior
    - No changes to external consumer APIs
    
  internal_changes:
    - MemoryStoreService class removed
    - Memory content stored directly in Agent instance  
    - Memory loading occurs only during initialization
    - LiveConfigManager absorbs ConfigurationWatcher functionality
    
  migration_requirements:
    - Existing code using Agent.memoryStore will need updates
    - Tests relying on MemoryStoreService need refactoring
    - Code expecting live memory updates must handle static content
    
  performance_implications:
    - Reduced memory overhead (no continuous file watching)
    - Faster agent initialization (simpler dependency chain)
    - One-time file I/O cost during startup
    - No ongoing file system monitoring overhead